import "@coinbase/onchainkit/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { UploadProvider } from "./context/Context";
import { WalletProvider } from "./context/WalletContext";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description:
    "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background dark">
        <Providers>
          <UploadProvider>
            <WalletProvider>{children}</WalletProvider>
          </UploadProvider>
        </Providers>
      </body>
    </html>
  );
}
